# Generated by Django 3.2.9 on 2021-11-30 10:53

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_remove_profile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
    ]
