# Generated by Django 4.0 on 2021-12-23 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverify',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
