# Generated by Django 4.0 on 2021-12-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Rotp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.CreateModel(
            name='otpstored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerotp', models.IntegerField()),
                ('forgototp', models.IntegerField()),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
