# Generated by Django 4.0 on 2021-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_rotp_remove_user_otp_otpstored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstored',
            name='forgototp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpstored',
            name='registerotp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
