# Generated by Django 4.0 on 2021-12-24 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_otpstored_forgototp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstored',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
