# Generated by Django 4.0 on 2021-12-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_otpstored_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstored',
            name='email',
        ),
    ]
