# Generated by Django 3.2.6 on 2021-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTo', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=16, null=True)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SendEmail',
            },
        ),
    ]
