# Generated by Django 3.2.9 on 2021-12-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='file',
            field=models.FileField(null=True, upload_to='Media'),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='sendTo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
